### ISSUE TITLE
Open to PR for multiprocessing?

### ISSUE THREAD

**Issue by jacobkimmel** [mrcinv/GSEA.py#3]
Hey @mrcinv,

I added optional parallelization support through `multiprocessing` to speed up computation.
Essentially, it adds a single API change:

```python
from gsea import gsea
# load D, C, S_sets, etc.
# ...

# runs using the existing serial computation
results = gsea(D, C, S_sets, n_jobs=1)
# runs with multiprocessing across gene sets
# using k processors
k = 2
results = gsea(D, C, S_sets, n_jobs=k)
# runs with multiprocessing across gene sets
# using all processors
results = gsea(D, C, S_sets, n_jobs=-1)
```

Would you be open to a PR incorporating those changes?

If so, I'm happy to make one.

Best,
Jacob

**Comment by mrcinv** [comment]
Yes, I'm open to MR, if you are willing to make one.

Best,
Martin

**Comment by jacobkimmel** [comment]
Sure thing, I'll open one now :).
